/**
 * Generates data/REVIEW_LIST.md — a human-readable table of all seed
 * universities sorted by acceptance_rate_overall, for the founder to
 * spot-check against current Common Data Set figures.
 *
 * Run: npx tsx scripts/generate-review-list.ts
 */

import { writeFileSync } from "node:fs";
import seed from "../data/universities.seed.json";

const FLAGGED_FOR_VERIFICATION: Record<string, string> = {
  mit: "Reinstated SAT/ACT requirement (2022); confirm 2025-26 cycle still requires testing.",
  harvard: "Reinstated testing for fall 2025; SAT/ACT bands here may lag the newest admitted class.",
  princeton: "Reinstated testing for fall 2025; verify current SAT/ACT 25th-75th bands.",
  brown: "Reinstated testing for fall 2025; verify current SAT/ACT 25th-75th bands.",
  caltech: "Extended test-blind policy through at least 2025; confirm it hasn't reverted to required.",
  "uc-berkeley": "UC system remains test-blind; verify acceptance rate and intl TOEFL minimum.",
  ucla: "UC system remains test-blind; verify acceptance rate (UCLA's is volatile year to year).",
  cornell: "Some Cornell colleges reinstated testing for 2025-26; test_policy here is a system-wide estimate.",
  upenn: "Penn announced need-blind admission for international applicants starting 2025-26; confirm rollout details and aid figures.",
  northeastern: "Acceptance rate has dropped sharply in recent cycles (~7%); verify against the latest CDS, not older reporting.",
};

type SeedRecord = (typeof seed)[number];

function fmtPct(n: number | null): string {
  return n === null ? "—" : `${n}%`;
}

function fmtMoney(n: number): string {
  return `$${n.toLocaleString("en-US")}`;
}

const sorted = [...(seed as SeedRecord[])].sort(
  (a, b) => a.acceptance_rate_overall - b.acceptance_rate_overall,
);

const header =
  "| Name | State | Type | Accept % (overall) | Accept % (intl) | SAT 25-75 | ACT 25-75 | Test policy | Cost (USD) | Intl aid policy | Source year |";
const divider =
  "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |";

const rows = sorted.map((u) => {
  const sat = u.sat25 === null || u.sat75 === null ? "—" : `${u.sat25}-${u.sat75}`;
  const act = u.act25 === null || u.act75 === null ? "—" : `${u.act25}-${u.act75}`;
  return [
    `| ${u.name}`,
    u.state,
    u.type,
    fmtPct(u.acceptance_rate_overall),
    fmtPct(u.acceptance_rate_intl),
    sat,
    act,
    u.test_policy,
    fmtMoney(u.cost_of_attendance_usd),
    u.intl_aid_policy,
    `${u.admission_source_year} |`,
  ].join(" | ");
});

const flaggedSection = Object.entries(FLAGGED_FOR_VERIFICATION)
  .map(([id, note]) => {
    const u = (seed as SeedRecord[]).find((r) => r.id === id);
    const name = u ? u.name : id;
    return `- **${name}** — ${note}`;
  })
  .join("\n");

const content = `# University Seed Review List

Generated by \`scripts/generate-review-list.ts\` from \`data/universities.seed.json\`.
All ${sorted.length} universities, sorted by overall acceptance rate (ascending).

${header}
${divider}
${rows.join("\n")}

## Verify these first

Admission statistics and testing policy at these ${Object.keys(FLAGGED_FOR_VERIFICATION).length}
schools have been especially volatile or subject to recent policy changes that
may postdate this assistant's training data. Check each against its current
Common Data Set / admissions page before relying on these numbers:

${flaggedSection}
`;

writeFileSync("data/REVIEW_LIST.md", content);
console.log(`Wrote data/REVIEW_LIST.md (${sorted.length} universities).`);
